hmcts/wa-case-event-handler

.gitignore, build.gradle, src/test/java/uk/gov/hmcts/reform/rsecheck/DemoUnitTest.java
Native library 'libnative-platform-file-events.so' could not be loaded for Linux amd64
```
[ ] Yes
[ x] No
```
=> RWA-49-fix: Attempt to fix issue in pipeline.

.gitignore, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/WelcomeTest.java, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/RootController.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/SpringBootFunctionalBaseTest.java
Added Base Functional test
Added application-functional.yaml to inject specific configuration using profiles
Added Serenity and junit 4 combination for functional tests
Fix no content type on root endpoint.
Added /target to git ignore
```
[ ] Yes
[x ] No
```
=> RWA-49a: Added welcome functional test

src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/DemoUnitTest.java
Fix unit test package name
```
[ ] Yes
[x ] No
```
=> RWA-49b: Fix unit test package name

Jenkinsfile_CNP, build.gradle, charts/wa-case-event-handler/Chart.yaml, charts/wa-case-event-handler/values.yaml, infrastructure/main.tf, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/config/ServiceTokenGeneratorConfigurationTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/ServiceTokenGeneratorConfiguration.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
Added Service to Service configuration and token generator. 
Added secret pull from s2s vault and copy into our wa-vault.
Updated jenkins file to pull from s2s vault.
```
[ ] Yes
[x ] No
```
=> RWA-49c: Setup S2S integration and secret pull from vault

src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/RootControllerTest.java
N/A
Increasing test coverage
```
[ ] Yes
[x ] No
```
=> Increasing test coverage

build.gradle
=> Fix sonar exclusions

charts/wa-case-event-handler/Chart.yaml, charts/wa-case-event-handler/values.yaml
Added s2s url on values.yaml
```
[ ] Yes
[x ] No
```
=> Added S2S url

Jenkinsfile_CNP
Enables tests reports to be archived
```
[ ] Yes
[x ] No
```
=> RWA-49d: Archiving test reports.

build.gradle
Added PiTest Mutation testing
```
[ ] Yes
[x ] No
```
=> RWA-49e: Added PiTest Mutation testing

Jenkinsfile_nightly, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-197
Upgrade azurerm to v2
```
[ ] Yes
[ x] No
```
=> RWA-197: Upgrade azurerm to v2

build.gradle, src/smokeTest/java/uk/gov/hmcts/reform/wataskmanagementapi/SmokeTest.java
Add smoke test
```
[ ] Yes
[x ] No
```
=> RWA-49g: Add smoke test

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerController.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/initiatetask/InitiateTaskEvaluateDmnRequest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/dates/IsoDateFormatter.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/WorkflowApiClientToInitiateTaskTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/dates/IsoDateFormatterTest.java
https://tools.hmcts.net/jira/browse/RWA-290
=> add junit test for the WorkflowApiClientToInitiateTask

build.gradle, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/initiatetask/InitiateTaskSendMessageRequestTest.java
=> add junit test for pojo

build.gradle, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/WorkflowApiClientToCancelTaskTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/cancellationtask/CancellationCorrelationKeysTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/cancellationtask/CancellationEvaluateRequestTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/cancellationtask/CancellationEvaluateResponseTest.java
https://tools.hmcts.net/jira/browse/RWA-305
=> RWA-305: add mutation coverage

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/WorkflowApiClientToCancelTask.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/cancellationtask/CancellationCorrelationKeys.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/cancellationtask/CancellationEvaluateResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/common/SendMessageRequest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/initiatetask/InitiateEvaluateResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/initiatetask/InitiateProcessVariables.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationTaskHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationTaskHandler.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/CancellationTaskHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/InitiationTaskHandlerTest.java
https://tools.hmcts.net/jira/browse/RWA-286
=> Feature/rwa 286 2: Add logic to cancel tasks 

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/WorkflowApiClientToCancelTask.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerController.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/cancellationtask/CancellationCorrelationKeys.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/cancellationtask/CancellationEvaluateResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/common/SendMessageRequest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/initiatetask/InitiateEvaluateResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/initiatetask/InitiateProcessVariables.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationTaskHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CaseEventHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationTaskHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningTaskHandler.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/CancellationTaskHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/InitiationTaskHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/WarningTaskHandlerTest.java
https://tools.hmcts.net/jira/browse/RWA-286
=> RWA-286 task categories to initiate and cancel tasks

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
=> added wait time for task creation

config/owasp/suppressions.xml
Remove redundant suppressions
```
[ ] Yes
[x ] No
```
=> Remove Suppressions

Jenkinsfile_nightly, audit.json, security.sh, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
=> Nightly dev

infrastructure/main.tf
Pull and Save ASB connection string in vault
```
[ ] Yes
[ x] No
```
=> Pull and Save ASB connection string in vault

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/CcdEventConsumer.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/ccd/CcdEventErrorHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/ccd/CcdEventProcessor.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/CcdEventConsumerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/ccd/CcdEventErrorHandlerTest.java
https://tools.hmcts.net/jira/browse/RWA-389
Handling unknown application errors
```
[ ] Yes
[ x] No
```
=> Catching uknown application errors

config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/CcdEventConsumer.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/ServiceBusConfiguration.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/ccd/CcdEventErrorHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/ccd/CcdEventProcessor.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/CcdEventConsumerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/ccd/CcdEventErrorHandlerTest.java
Improve logging messages
```
[ ] Yes
[x ] No
```
=> Improve logging messages

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
Set eventId to dynamic value
```
[ ] Yes
[ ] No
```
=> Set eventId to dynamic value

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/initiatetask/InitiateProcessVariables.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationTaskHandler.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/InitiationTaskHandlerTest.java
Rename casetype to caseTypeId
```
[ ] Yes
[x ] No
```
=> Rename casetype to caseTypeId

README.md, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
=> udpated readme file

audit.json, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationTaskHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationTaskHandler.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/WorkflowApiClientToCancelTaskTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/WorkflowApiClientToInitiateTaskTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/WorkflowApiClientToWarnTaskTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/CancellationTaskHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/InitiationTaskHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/WarningTaskHandlerTest.java
https://tools.hmcts.net/jira/browse/RWA-470
```
[ ] Yes
[x ] No
```
=> ignoring security in nighlty build. Added few more tests

charts/wa-case-event-handler/Chart.yaml, charts/wa-case-event-handler/values.yaml
https://tools.hmcts.net/jira/browse/RWA-475
Add launch darkly sdk key from vault
```
[ ] Yes
[ x] No
```
=> RWA-475: add secret to values.yaml

charts/wa-case-event-handler/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-496
Bump hmctspublic java chart version
```
[ ] Yes
[x ] No
```
=> RWA-496: Bump hmctspublic java chart version

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerEndPointTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/common/AdditionalData.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/common/EventInformation.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/initiatetask/InitiateEvaluateRequest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationTaskHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/DueDateService.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/EvaluateDmnRequestToInitiateTaskTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/EventInformationTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/cancellationtask/AdditionalDataTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/helpers/InitiateTaskHelper.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/DueDateServiceTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/InitiationTaskHandlerTest.java, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/evaluate-dmn-request.json, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/evaluate-dmn-response.json, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/expected-event-information-additional-data.json, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/valid-event-information-additional-data.json
https://tools.hmcts.net/jira/browse/RWA-437
Calculating delayDuration to delay the tasks.
```
[ ] Yes
[x] No
```
=> RWA-437 : Calculating delayDuration

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/ccd/CcdEventProcessor.java
Enable additional data log
```
[ ] Yes
[ ] No
```
=> Enable additional data log

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/common/DmnBooleanValue.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/initiatetask/InitiateProcessVariables.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationTaskHandler.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/cancellationtask/common/DmnStringValueTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/handlers/common/DmnBooleanValueTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/InitiationTaskHandlerTest.java
https://tools.hmcts.net/jira/browse/RWA-524
=> add hasWarnings to the Initiate task message

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/ccd/CcdEventProcessor.java
Fix CVE-2021-21290, CVE-2021-21295, CVE-2021-21409 by updating by dependancyManagement
```
[ ] Yes
[x ] No
```
=> Fix: CVE-2021-21290, CVE-2021-21295, CVE-2021-21409

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/ia/CaseEventFieldsDefinition.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationTaskHandler.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/helpers/InitiateTaskHelper.java
=> update field name to be dateDue

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/DueDateService.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/DueDateServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-545
Calculating DelayUntil with calendar days
```
[ ] Yes
[x ] No
```
=> RWA-545 Hotfix : Calculating DelayUntil with calendar days

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerEndPointTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/WorkflowApiClient.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/request/SendMessageRequest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/CancellationEvaluateResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/EvaluateDmnResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/InitiateEvaluateResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationCaseEventHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/ccd/CcdEventProcessor.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/holidaydates/CountryHolidayDates.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/holidaydates/HolidayDate.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/holidaydates/UkHolidayDates.java, src/main/resources/application-local.yaml, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationCaseEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerTest.java
Fix generic responses in Feign client for evaluate dmn
```
[ ] Yes
[x ] No
```
=> Fix generic responses in Feign client for evaluate dmn

src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerEndPointTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/CancellationEvaluateResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/InitiateEvaluateResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandler.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationCaseEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerTest.java
Changes to support new multicategory format
```
[ ] Yes
[ x] No
```
=> RWA-532-c: Changes to support new multicategory format

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-563
=> fix functional test

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
Ignore functional tests with non-existing requirement
```
[ ] Yes
[ x] No
```
=> Ignore functional tests with non-existing requirement

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-634
=> updated FT

Jenkinsfile_nightly, security.sh
Fix nightly build failure
```
[ ] Yes
[ X] No
```
=> Fix nightly build failure

security.sh
Update functional output syntax
```
[ ] Yes
[ X] No
```
=> Update functional output synthax

build.gradle
=> CVE-2021-27568 fix for json-smart library

charts/wa-case-event-handler/values.yaml, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerBackwardsCompatibilityTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerEndpointTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/Warning.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/WarningValues.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/CancellationEvaluateResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandler.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandler.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/WarningTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/WarningValuesTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationCaseEventHandlerBackwardsCompatibilityTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationCaseEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandlerBackwardsCompatibilityTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerBackwardsCompatibilityTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerTest.java
https://tools.hmcts.net/jira/browse/RWA-604
```
[ ] Yes
[x ] No
```
=> Updated warning handler to add warnings as process variables

build.gradle
=> Nightly fx

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/config/SwaggerPublisherTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerBackwardsCompatibilityTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerEndpointTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerHandlersOrderTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerSecurityTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/GetWelcomeTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerController.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-645
=> add swagger api docs

audit.json
Ignore rule as all endpoints should be authenticated therefore expected behaviour
```
[ ] Yes
[x ] No
```
=> Fix Nighly build

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandler.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerTest.java
=> fix sonar issues

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RWA-626
```
[ ] Yes
[x ] No
```
=> Updated nightly build to run FTs

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerBackwardsCompatibilityTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerEndpointTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/EventInformationTest.java, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/expected-event-information-additional-data.json, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/valid-event-information-additional-data.json
https://tools.hmcts.net/jira/browse/RWA-709
```
[ ] Yes
[x ] No
```
=> Added new fields to Additonal Data in FT

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/WarningEventHandlerControllerTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerController.java
https://tools.hmcts.net/jira/browse/RWA-728
=> enable first non-requirement FT

charts/wa-case-event-handler/Chart.yaml, charts/wa-case-event-handler/values.yaml, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/CcdCaseEventsConsumer.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/CcdCaseEventsExecutor.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/ServiceBusConfiguration.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/CcdCaseEventConsumerTest.java
https://tools.hmcts.net/jira/browse/RWA-990
Consume message from new subscription created in RWA-923
```
[ ] Yes
[X ] No
```
=> RWA-990 - Consume messages from new ccd-case-events subscription

audit.json
https://tools.hmcts.net/jira/browse/RWA-1011
```
[ ] Yes
[X] No
```
=> audit.json updated for security issues

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/CcdCaseEventsDeadLetterQueueExecutor.java
https://tools.hmcts.net/jira/browse/RWA-999
fix duplicate bean error
```
[ ] Yes
[X] No
```
=> RWA-999 - fix duplicate bean error

Jenkinsfile_nightly, build.gradle, config/config/config/fortify-client.properties, config/fortify-client.properties
[RWA-712](https://tools.hmcts.net/jira/browse/RWA-712)
[RWA-712](https://tools.hmcts.net/jira/browse/RWA-712)
```
[ ] Yes
[ X] No
```
=> RWA-712 Integrate with Fortify

src/main/resources/db/migration/V20220105_1030__RWA-1030-add_indices.sql
https://tools.hmcts.net/jira/browse/RWA-1030
Add indexes on columns in wa_case_event_messages table
```
[ ] Yes
[X] No
```
=> RWA-1030 - Add indexes on columns in wa_case_event_messages table

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerEndpointTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/InitiateEvaluateResponse.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandler.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandlerBackwardsCompatibilityTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/helpers/InitiateTaskHelper.java, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/camunda/response/evaluate-dmn-response.json
https://tools.hmcts.net/jira/browse/RWA-722
Remove group field
```
[ ] Yes
[ ] No
```
=> feat:Remove group usage(RWA-722)

audit.json
https://tools.hmcts.net/jira/browse/RWA-1050
adding lines to audit.json
```
[ ] Yes
[ x] No
```
=> RWA-1050 [SH] fixing nightly build

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/LaunchDarklyFeatureFlagProvider.java
https://tools.hmcts.net/jira/browse/RWA-930
Change constant name to satisfy fortify scan
```
[ ] Yes
[X] No
```
=> RWA-930 - Change constant name to satisfy fortify scan

charts/wa-case-event-handler/Chart.yaml
Up the java chart version
```
[ ] Yes
[ ] No
```
=> Refactor:Up the java chart version

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/config/LaunchDarklyFeatureFlagProviderTest.java
https://tools.hmcts.net/jira/browse/RWA-1148
```
[ ] Yes
[ ] No
```
=> RWA-1148: Fix case event handler

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/EventMessageQueryService.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/EventMessageReceiverService.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/IdempotencyKeyGenerator.java
resolve cve issues
```
[ ] Yes
[ ] No
```
=> refactor:resolve cve issues

charts/wa-case-event-handler/Chart.yaml
=> Bump java chart

audit.json, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1167
```
[ ] Yes
[X] No
```
=> suppress CWE-862

build.gradle, config/checkstyle/checkstyle.xml, gradle/wrapper/gradle-wrapper.properties, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/config/OpenAPIPublisherTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/config/SwaggerPublisherTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/OpenAPIConfiguration.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/SwaggerConfiguration.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerController.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerTestingController.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/DatabaseMessageConsumerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/repository/CaseEventMessageCustomCriteriaRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/repository/CaseEventMessageRepositoryTest.java
https://tools.hmcts.net/jira/browse/RWA-982
Spring boot upgrade
```
[ ] Yes
[x ] No
```
=> RWA-982 [SH] Upgrading springboot version to 2.6 and openfeign to 3.0.6

charts/wa-case-event-handler/Chart.yaml, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/MessageProcessorFunctionalTest.java
=> RWA-1194 Get the case even handler build to green

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1271
Supressed CVE for postgres temporarily. JIRA ticket covers CEH and Workflow API
```
[ ] Yes
[X ] No
```
=> RWA-1271 Suppress postgres CVE

src/functionalTest/resources/requests/ccd/case_data.json
https://tools.hmcts.net/jira/browse/RWA-1171
RWA-1171 add-waDummyPostcode
```
[ ] Yes
[X] No
```
=> RWA-1171-add-waDummyPostcode

build.gradle, charts/wa-case-event-handler/Chart.yaml, charts/wa-case-event-handler/values.yaml
https://tools.hmcts.net/jira/browse/RWA-1098
Autoscaling for R1
```
[ ] Yes
[X] No
```
=> RWA-1098-autoscaling for R1

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerTestingControllerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/SpringBootFunctionalBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-1313
```
[ ] Yes
[ ] No
```
=> RWA-1313 Check Idempotency key is being generated and passed correctly by DLQ message process

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/DatabaseMessageConsumer.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/MessageReadinessConsumer.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/executors/CcdMessageProcessorExecutor.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/executors/MessageReadinessExecutor.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-1225
```
[ ] Yes
[ ] No
```
=> RWA-1225: Improve performance of post-deployment-test

src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/repository/CaseEventMessageCustomCriteriaRepositoryTest.java
https://tools.hmcts.net/jira/browse/RWA-1316
fixed disabled tests
```
[ ] Yes
[x] No
```
=> RWA-1316 fixed disabled tests

.github/dependabot.yml
Changed dependabot schedule to weekly.
Disabled automatic rebase of dependabot PRs.
Cleaned up dependabot configuration.
```
[ ] Yes
[x ] No
```
=> Dependabot configuration changes

build.gradle
=> RWA-1402 supress netty-transport

build.gradle, config/owasp/suppressions.xml
=> RWA-1408 - CVE-2016-1000027 supression

build.gradle
=> RWA-1426 - upgrade springframework boot version 2.6.7 -> 2.7.0

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/ProblemMessageControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/MessageProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/config/CcdMessageProcessorExecutorTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/config/MessageReadinessExecutorTest.java
=> RWA-1434: Deployment:- Verify DLQ solution is switched on in AAT 

infrastructure/main.tf, infrastructure/variables.tf
Product name should be wa.
The DB should also use this product name so we can access it from prod (this is the convention used).
=> The product name should be wa.

build.gradle
https://tools.hmcts.net/jira/browse/RWA-1523
RWA-1523: fixed fortifyScan scan
```
[ ] Yes
[x] No
```
=> RWA-1523: fixed fortifyScan error

config/owasp/suppressions.xml
=> RWA-1635 - supress RWA-1635 - supress

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/RestExceptionCategory.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/RestExceptionCategoryTest.java
https://tools.hmcts.net/jira/browse/RWA-1611
```
[ ] Yes
[ ] No
```
=> RWA-1611: Handle "Token expired" exception

src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/services/DueDateServiceTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/DueDateService.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/DueDateServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-1584
```
[ ] Yes
[X] No
```
=> RWA-1584-consider holiday and weekends when calculating delay duration

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandler.java
[RWA-1615](https://tools.hmcts.net/jira/browse/RWA-1615)
See ticket 
```
[ ] Yes
[ X] No
```
=> Increase logs

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/SpringBootFunctionalBaseTest.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/config/GivensBuilder.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/services/AuthorizationProvider.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/utils/Common.java
[RWA-1069](https://tools.hmcts.net/jira/browse/RWA-1069)
```
[ ] Yes
[x] No
```
=> RWA-1069 Re-visit the CEH FTs which are marked as @Ignore

build.gradle
https://tools.hmcts.net/jira/browse/RWA-1699
CVE fix for postgres database driver
```
[ ] Yes
[X] No
```
=> RWA-1699 CVE fix

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java, src/functionalTest/resources/requests/roleAssignment/r2/set-organisational-role-assignment-request.json, src/functionalTest/resources/requests/roleAssignment/set-organisational-role-assignment-request.json
[RWA-1624](https://tools.hmcts.net/jira/browse/RWA-1624)
```
[ ] Yes
[ ] No
```
=> RIA-1624 clean up Role Assignments in AAT

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerTestingControllerFunctionalTest.java
[RWA-1521](https://tools.hmcts.net/jira/browse/RWA-1521)
```
[ ] Yes
[x] No
```
=> RWA-1521 Camunda - Switch off Task configuration code

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/AsbMessagesToDatabaseTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/MessageProcessorFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerFunctionalTestHelper.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerTestingControllerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/WarningEventHandlerControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/ProblemMessageControllerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/DatabaseMessageConsumerTest.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/MessagingTests.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/SpringBootFunctionalBaseTest.java
https://tools.hmcts.net/jira/browse/RWA-1711
Several test changes to make them more reliable
```
[ ] Yes
[X] No
```
=> Rwa 1711 Test improvements

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/AsbMessagesToDatabaseTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/DlqMessagesToDatabaseTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/MessageProcessorFunctionalTest.java
Use created ccd cases Id in functional tests
```
[ ] Yes
[ ] No
```
=> Use created ccd cases Id in functional tests

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerTestingControllerFunctionalTest.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/MessagingTests.java
Remove random caseId generation from functional tests
```
[ ] Yes
[ ] No
```
=> Remove random caseId generation from functional tests

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/model/TaskOperation.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/ReconfigurationCaseEventHandler.java
[RWA-1824](https://tools.hmcts.net/jira/browse/RWA-1824)
see ticket
```
[ ] Yes
[ X] No
```
=> RWA-1824 Fix Reconfiguration issue

build.gradle
Reverting merge to master without QA approval
=> RWA 1938 (#387)

build.gradle
https://tools.hmcts.net/jira/browse/RWA-1967
To fix  CVE-2022-31692 and CVE-2022-31690 with spring-security-config spring-security-core,  spring-security-crypto and spring-security-web upgraded from version 5.7.4 to version 5.7.5
To fix CVE-2022-42252 with tomcat-embed-core and tomcat-embed-websocket upgraded from version 9.0.64 to version 9.0.68
```
[ ] Yes
[ x ] No
```
=> RWA-1967 fix cve issues

src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerHandlersOrderTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/EventInformation.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/EventInformationTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/EventMessageReceiverServiceTest.java, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/expected-event-information-additional-data.json, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/expected-event-information-from-ccd.json, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/valid-event-information-additional-data.json, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/valid-event-information.json
https://tools.hmcts.net/jira/browse/RWA-1921
Avoid Timestamp comparison trailing zero errors
```
[ ] Yes
[X] No
```
=> RWA-1921 fix timestamp rounding issue

src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerHandlersOrderTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/EventInformation.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/EventInformationTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/EventMessageReceiverServiceTest.java, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/expected-event-information-additional-data.json, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/expected-event-information-from-ccd.json, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/valid-event-information-additional-data.json, src/test/resources/uk/gov/hmcts/reform/wacaseeventhandler/domain/ccd/message/valid-event-information.json
https://tools.hmcts.net/jira/browse/RWA-1985
Revert timestamp format causing prod issue
```
[ ] Yes
[X] No
```
=> RWA-1985: revert troublesome timestamp format

src/functionalTest/resources/application-functional.yaml, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/DatabaseMessageConsumerResilienceTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/MessageReadinessResilienceTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/MessageReadinessTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/EventConsumerIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/ProblemMessageControllerTest.java, src/main/resources/application.yaml
[RWA-1995](https://tools.hmcts.net/jira/browse/RWA-1995)
Remove old subscription usage from tests 
```
[ ] Yes
[ ] No
```
=> Remove old subscription usage from tests (RWA-1995)

build.gradle
https://tools.hmcts.net/jira/browse/RWA-2060
CVE FIX - CVE-2022-41946 - upgrade postgresql 42.4.3
```
[ ] Yes
[x] No
```
=> RWA-2060 - CVE FIX - CVE-2022-41946 - upgrade postgresql 42.4.3

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2129
Suppressed changes that needed a change of version to Spring Boot to version 3.x.x
Moved tomcat to version '9.0.69',
```
[ ] Yes
[ x ] No
```
=> RWA-2129 resolve CVE issues

gradle/wrapper/gradle-wrapper.properties
Updating Gradle Version to 7.6
```
[ ] Yes
[X] No
```
=> RWA-2127 Updating Gradle Version to 7.6

build.gradle
Update OWASP   Dependency check
```
[ ] Yes
[X ] No
```
=> update owasp dependencycheck

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/MessageProcessorFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerFunctionalTest.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/MessagingTests.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/utils/Common.java
https://tools.hmcts.net/jira/browse/RWA-2158
```
[ ] Yes
[X] No
```
=> RWA-2158 add some logs to fix non removed message ids

README.md
https://tools.hmcts.net/jira/browse/RWA-2276
```
[ ] Yes
[X] No
```
=> RWA-2276-readme file arranged

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerTestingControllerFunctionalTest.java
[RWA-2231](https://tools.hmcts.net/jira/browse/RWA-2231)
see ticket [RWA-2231](https://tools.hmcts.net/jira/browse/RWA-2231)
```
[ ] Yes
[X ] No
```
=> RWA-2231: Enable debug mode

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/DelayTasksBasedOnDelayUntilTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/InitiationCaseEventHandler.java
[RWA-2452](https://tools.hmcts.net/jira/browse/RWA-2452)
Test delay until date issue
```
[ ] Yes
[ ] No
```
=> Test delay until date issue

Jenkinsfile_nightly
=> Multi gitter branch

build.gradle
https://tools.hmcts.net/jira/browse/RWA-2706
Fix CVEs CVE-2023-34034, CVE-2020-8908
```
[ ] Yes
[ x ] No
```
=> RWA-2655: Fix CVEs CVE-2023-34034, CVE-2020-8908

Jenkinsfile_CNP, audit.json, build.gradle
https://tools.hmcts.net/jira/browse/RWA-2759
```
[ ] Yes
[ x] No
```
=> Fix CVE-2023-41080 

build.gradle
https://tools.hmcts.net/jira/browse/RWA-2765
Upgrade java logging version
```
[ ] Yes
[x] No
```
=> RWA-2765-upgrade java logging

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2856
wa-case-event-handler master pipeline build failure
```
[ ] Yes
[x] No
```
=> RWA-2856- wa-case-event-handler master pipeline build failure

charts/wa-case-event-handler/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-2845
Migrating to Workload Identity
```
[ ] Yes
[x] No
```
=> RWA-2845 Migrating to Workload Identity

src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/services/calendar/DelayUntilConfiguratorTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/calendar/DelayUntilCalculator.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/calendar/DelayUntilConfigurator.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/calendar/DelayUntilDateTimeCalculator.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/calendar/DelayUntilIntervalCalculator.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/calendar/DelayUntilConfiguratorTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/calendar/DelayUntilDateTimeCalculatorTest.java
https://tools.hmcts.net/jira/browse/RWA-2862
Failure in case event handler, functional test
```
[x] Yes
[ ] No
```
=> RWA-2845 updated localdatetime

build.gradle
https://tools.hmcts.net/jira/browse/RWA-3015
Need to upgrade OWASP - wa-case-event handler
```
[ ] Yes
[x] No
```
=> RWA-3015 Need to upgrade OWASP - wa-case-event handler

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/DatabaseMessageConsumer.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/MessageReadinessConsumer.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/executors/MessageReadinessExecutor.java
https://tools.hmcts.net/jira/browse/RWA-3047
Log level changes, initial delay and exception logging on readiness checker
```
[ ] Yes
[ x ] No
```
=> RWA-3047: Log level changes, initial delay and exception logging on readiness checker

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3089
```
[ ] Yes
[x] No
```
=> RWA-3089: Fix suppressions

build.gradle
https://tools.hmcts.net/jira/browse/RWA-3113
=> Bumping spring sec to fix CVE

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RWA-2932
Remove Postgres single server infra.
```
[ ] Yes
[ x] No
```
=> RWA-2932: Remove Postgres single server infra.

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerLivenessHealthController.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerReadinessHealthController.java
https://tools.hmcts.net/jira/browse/RWA-3130
Adding logs for app-insight alert messages
```
[ ] Yes
[ x ] No
```
=> RWA-3130: Adding app-insight alert messages

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3147
Extend CVE-2023-36052
```
[ ] Yes
[x] No
```
=> RWA-3145: Extend suppression

build.gradle, charts/wa-case-event-handler/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-3209
```
[ ] Yes
[ x] No
```
=> RWA-3209: Upgrade postgresql

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3227
```
[ ] Yes
[X] No
```
=> RWA-3227: Extend Suppression

src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/ReceivedMessagesHealthControllerStagingEnvTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/ReceivedMessagesHealthController.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/ReceivedMessagesHealthControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-3295
```
[ ] Yes
[ ] No
```
=> RWA-3295: Added staging env check for receivedMessages api

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/ReceivedMessagesHealthController.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/ReceivedMessagesHealthControllerTest.java
https://tools.hmcts.net/jira/browse/RWA-3299 
```
[ ] Yes
[ ] No
```
=> Rwa 3299 health check time correction

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3325
```
[ ] Yes
[x] No
```
=> RWA-3325: Extend Suppression

build.gradle
https://tools.hmcts.net/jira/browse/RWA-3444
```
[ ] Yes
[ ] No
```
=> RWA-3444: properties-volume-spring-boot-starter removal

Jenkinsfile_CNP, Jenkinsfile_nightly, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3486
```
[ ] Yes
[x ] No
```
=> RWA-3486: Add env.TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX

.github/renovate.json
https://tools.hmcts.net/jira/browse/RWA-3559
=> tune renovate

build.gradle, gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/RWA-3520
```
[ ] Yes
[X] No
```
=> RWA-3520: Upgrade dependencycheck to 10.0.2

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/MessageProcessorFunctionalTest.java
https://tools.hmcts.net/jira/browse/RWA-3683
=> Disabling test

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/LaunchDarklyFeatureFlagProvider.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/EventMessageQueryService.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/holidaydates/HolidayLoader.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/repository/CaseEventMessageCustomCriteriaRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/repository/CaseEventMessageErrorHandlingRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/EventMessageQueryServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-3564
Fix easy sonar issues
```
[ ] Yes
[x] No
```
=> RWA-3564 fix easy code smells

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerFunctionalTest.java
https://tools.hmcts.net/jira/browse/RWA-2310
```
[ ] Yes
[ ] No
```
=> Camunda tests fix

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerFunctionalTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/DatabaseMessageConsumerTest.java
https://tools.hmcts.net/jira/browse/RWA-3755
```
[ ] Yes
[ ] No
```
=> RWA-3755: Flaky test fix

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3763
```
[ ] Yes
[x] No
```
=> RWA-3763: Extend Suppression

build.gradle
https://tools.hmcts.net/jira/browse/RWA-3800 
```
[ ] Yes
[ ] No
```
=> Degrading LaunchDarkly to 6.2.1

src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/query/ResetProblemMessageTest.java, src/integrationTest/resources/scripts/reset_problem_messages_data.sql
https://tools.hmcts.net/jira/browse/RWA-3782 
```
[ ] Yes
[ ] No
```
=> RWA-3782: ResetProblemMessageTest Fix

src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/query/ProblemMessageServiceTest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/model/ExecuteReconfigureTaskFilter.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/model/TaskOperation.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/model/TaskOperationRequest.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/FindProblemMessageJob.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/ResetNullEventTimestampMessageJob.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/ResetProblemMessageJob.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/DatabaseMessageConsumerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/domain/model/ProblemMessageTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationCaseEventHandlerBackwardsCompatibilityTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/CancellationCaseEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerBackwardsCompatibilityTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/handlers/WarningCaseEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/repository/CaseEventMessageErrorHandlingRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/repository/CaseEventMessageRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/EventMessageReceiverServiceTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/UpdateRecordErrorHandlingServiceTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/holidaydates/CountryHolidayDatesTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/holidaydates/HolidayDateTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/CleanUpMessageJobTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/FindProblemMessageJobTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/ProblemMessageServiceTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/ResetNullEventTimestampMessageJobTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/ResetProblemMessageJobTest.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/SetStateToProcessedMessageJobTest.java, src/testUtils/java/uk/gov/hmcts/reform/wacaseeventhandler/services/AuthorizationProvider.java
https://tools.hmcts.net/jira/browse/RWA-3813
Reduce SonarCloud Code Smells - wa-case-event-handler Sep24
```
[x] Yes
[ ] No
```
=> RWA-3813 Fix code smells

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3884
extend cve suppression
```
[ ] Yes
[x] No
```
=> RWA-3884 extend cve suppression

src/main/resources/scripts/RWA-3871_reinstate-msg-content.sql, src/main/resources/scripts/RWA-3871_reinstate-msg-content_rollback.sql
https://tools.hmcts.net/jira/browse/RWA-3871
=> Reinstating msg content statements

.github/renovate.json
https://tools.hmcts.net/jira/browse/RWA-4056
update renovate config
```
[ ] Yes
[x] No
```
=> RWA-4056 update renovate

src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/LaunchDarklyFeatureFlagProvider.java, src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/LaunchDarklyFeatureFlagProviderTest.java
https://tools.hmcts.net/jira/browse/RWA-3801 
```
[ ] Yes
[ ] No
```
=> RWA-3801: LaunchDarkly Sonar fixes

build.gradle, lib/applicationinsights.json, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/clients/CcdCaseEventsConsumer.java, src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/config/ServiceBusConfiguration.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-4101
=> Rwa 4101 lower servicebus logs

charts/wa-case-event-handler/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-4201
Upgrading to oci chart
bumping java chart version
```
[ ] Yes
[x] No
```
=> RWA-4201: upgrading to oci chart

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RWA-4283
Update main.tf
```
[ ] Yes
[x] No
```
=> RWA-4283 update main.tf

CODEOWNERS
https://tools.hmcts.net/jira/browse/RWA-4241
Added WA team as codeowners
```
[ ] Yes
[x] No
```
=> RWA-4241: Added codeowners

SECURITY.md
https://tools.hmcts.net/jira/browse/RWA-4240
```
[ ] Yes
[x] No
```
=> RWA-4240: Added Security.md

build.gradle
https://tools.hmcts.net/jira/browse/RWA-4382
Fix upgrade pitest library issues 
```
[ ] Yes
[x] No
```
=> RWA-4382 upgrade pitest library issues

build.gradle
https://tools.hmcts.net/jira/browse/RWA-4366
Upgrade owasp
```
[ ] Yes
[x] No
```
=> RWA-4366: Upgrade owasp

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/DelayTasksBasedOnDelayUntilTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/ReceivedMessagesHealthControllerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/services/calendar/CalendarCacheManagerTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/services/calendar/DelayUntilConfiguratorTest.java, src/integrationTest/java/uk/gov/hmcts/reform/wacaseeventhandler/services/calendar/PublicHolidaysCollectionTest.java
https://tools.hmcts.net/jira/browse/RWA-4638
=> Fixing holiday tests

src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerFunctionalTest.java
https://tools.hmcts.net/jira/browse/RWA-4633 
```
[ ] Yes
[ ] No
```
=> RWA-4567: Tests refactor

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RWA-4705
Enable QPI on AAT
```
[ ] Yes
[x] No
```
=> Enable Query Performance Insights on AAT.
